### ISSUE TITLE
Not work with Django-current, "cannot import name get_standard_processors"

### ISSUE THREAD

**Issue by nnmware** [django-debug-toolbar/django-debug-toolbar#668]
After "Encapsulated TEMPLATE_CONTEXT_PROCESSORS in Engine." https://github.com/django/django/commit/37505b6397058bcc3460f23d48a7de9641cd6ef0 debug panel not work with current version of Django.

django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.templates: "cannot import name get_standard_processors"

**Comment by alexbarton** [comment]
This problem still occurs with Django 1.8a1, which has been released yesterday:

    File "…/debug_toolbar/panels/templates/panel.py", line 16, in <module>
        from django.template.context import get_standard_processors
    ImportError: cannot import name 'get_standard_processors'

**Comment by hobson** [comment]
Same here on master branch of django-debug-toolbar and released Django 1.8a1

**Comment by HarinderToor** [comment]
Also getting this problem.

Seems to already be a pull request to fix this issue here: https://github.com/django-debug-toolbar/django-debug-toolbar/pull/674

**Comment by joelburton** [comment]
Reproducible with 1.8b1. It would help widespread testing of 1.8 betas for the toolbar to be working; is there something we can do to help improve the referenced PR so it can be included?

**Comment by aaugustin** [comment]
As of 22473d36346901b3320f1bf25f4f602d8ded6d04 tests pass on Django 1.8 beta 1.

**Comment by Charlex** [comment]
If I were still running into this after an upgrade to 1.8, what should I do? 

Code: 

```
    # Debugging toolbar middleware
    MIDDLEWARE_CLASSES += (
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    )
    # JavaScript panels for the deveopment debugging toolbar
    DEBUG_TOOLBAR_PANELS = (
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
    )
    # Debug toolbar app
    CONFIG_DEFAULTS = {
        'INTERCEPT_REDIRECTS': False,
    }
```

**Comment by tim-schilling** [comment]
What version of the toolbar are you using?

**Comment by banjocat** [comment]
To get this to work on my end I had to add INTERNAL_IPS = ('myip')
I am running django 1.8.4 with django-debug-toolbar 1.3.2

Updating to debug-toolbar 1.4 made django update to 1.9

I based this on teammates code base. So I can not say why this worked.
