### ISSUE TITLE
Cannot import name import_string

### ISSUE THREAD

**Issue by pedroseac** [django-debug-toolbar/django-debug-toolbar#768]
I'm trying to start my application, but keep getting this error:

Unhandled exception in thread started by <function wrapper at 0x1084b9320>
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 93, in wrapper
    fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/runserver.py", line 98, in inner_run
    self.validate(display_num_errors=True)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/Library/Python/2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Library/Python/2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/Library/Python/2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/Library/Python/2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Library/Python/2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/debug_toolbar/models.py", line 5, in <module>
    from debug_toolbar import settings as dt_settings
  File "/Library/Python/2.7/site-packages/debug_toolbar/settings.py", line 8, in <module>
    from django.utils.module_loading import import_string
ImportError: cannot import name import_string

Any ideas?

**Comment by aaugustin** [comment]
Are you using compatible versions of Django and of the debug toolbar?

**Comment by smanjil** [comment]
I have django 1.5 and debug_toolbar 1.4

**Comment by priya124** [comment]
how to solve this i do not using any toolbar i got the same error while i'm installing RatticDB on ubuntu 12.04

**Comment by gnemoug** [comment]
have the problem in mac(django==1.5.7)

**Comment by gnemoug** [comment]
this function add in Since Django 1.7

**Comment by smanjil** [comment]
use django1.5 with django-debug-toolbar 1.0.1

u can install it with 'pip install django-debug-toolbar==1.0.1'

**Comment by gnemoug** [comment]
use django1.5 with django-debug-toolbar 1.3.2

**Comment by anentropic** [comment]
is there a list somewhere of which debug toolbar versions work with which django versions?

I need one that works with Django 1.4 😿

**Comment by anentropic** [comment]
ok it seems I need 1.3.2
